#
# Ansible Dockerfile
#
# https://github.com/dockerfile/ansible
#

# Pull base image.
FROM python:3.14.0a2-bullseye

# Install Ansible.
RUN pip3 install ansible

# Define working directory.
WORKDIR /data

# Define default command.
CMD ["bash"]